name: Pull Request Template
description: Use this template for submitting pull requests.

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a brief description of the changes introduced by this PR.
    validations:
      required: true

  - type: input
    id: related_issue
    attributes:
      label: Related Issue
      description: If this PR addresses or is related to an existing issue, please link to it. If this PR creates a new component, it's mandatory that you link the approved 'New Component Proposal' ticket.
      placeholder: e.g. #123

  - type: checklist
    id: checklist
    attributes:
      label: Checklist
      description: Please ensure that the following tasks are completed before submitting your PR.
      options:
        - label: I have read and understood the [Contribution Guidelines](../../docs/CONTRIBUTING.md).
        - label: I have followed the [Design Guidelines](../../docs/DESIGN_GUIDELINES.md).
        - label: I have followed the [Code Guidelines](../../docs/CODE_GUIDELINES.md).
        - label: I have added necessary documentation (if applicable).
        - label: I have ensured that my code follows the project's coding standards.

  - type: textarea
    id: implementation_details
    attributes:
      label: Implementation Details
      description: Provide details about the implementation, including any design decisions and rationale.
      placeholder: |
        Component Name: [Component Name]
        Key Features:
        - Feature 1
        - Feature 2
        - Feature 3

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Visual Changes
      description: If applicable, include screenshots/recordings to illustrate the visual changes introduced by this PR.
      placeholder: |
        Before: ![Before Screenshot](link_to_before_screenshot)
        After: ![After Screenshot](link_to_after_screenshot)

  - type: textarea
    id: testing_instructions
    attributes:
      label: Testing Instructions
      description: Provide detailed instructions on how to test the changes made by this PR.
      placeholder: |
        1. Step 1
        2. Step 2
        3. Step 3
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Include any additional information or context that reviewers should be aware of.
      placeholder: Any known issues or limitations \n Dependencies or related PRs

  - type: checklist
    id: reviewer_checklist
    attributes:
      label: Reviewer Checklist
      description: For reviewers to ensure that all necessary aspects have been covered.
      options:
        - label: Code follows the project's coding standards.
        - label: Documentation has been added or updated.
        - label: Visual changes have been reviewed and approved by the UX team.
        - label: No breaking changes or backward compatibility issues.
