name: 🐛 Bug Report
description: Report a bug
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Provide a detailed list of steps that reproduce the issue.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: |
        Provide screenshots/recordings of the bug if possible.
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Provide information about your environment, Run `npx/yarn shop-minis` and paste the output.
    validations:
      required: true
