name: 🆕 Feature Request
description: Request a feature
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a brief description of the feature you would like to see implemented.
    validations:
      required: true
  - type: textarea
    id: usecases
    attributes:
      label: Use Cases
      description: Describe the use cases for this feature. How will it benefit users or improve the Shop Minis platform?
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Include any additional information or context that reviewers should be aware of.
